apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmasters-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devmasters
  template:
    metadata:
      labels:
        app: devmasters
    spec:
      containers:
      - name: webapp
        image: juanmiluque/devmasters-producto2:latest
        ports:
        - containerPort: 8080
